service: thumbnail-api
# app and org for use with dashboard.serverless.com
app: thumbnail-api
org: skaznowiecki

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage,'dev'}
  region: us-east-1
  environment:
    BUCKET: ${file(./.env.yml):BUCKET}
    BASE_PATH: ${file(./.env.yml):BASE_PATH}
    REGION: ${file(./.env.yml):REGION}
    ACCESS_KEY: ${file(./.env.yml):ACCESS_KEY}
    SECRET_KEY: ${file(./.env.yml):SECRET_KEY}
    
outputs:
  custom-output: any-value-here


# Add the serverless-webpack plugin
#plugins:
#  - serverless-webpack

functions:
  store:
    handler: handlers/api.store
    events:
      - http:
          path: thumbs
          method: post
          cors: true
    environment:
      MAX_SIZE: ${file(./.env.yml):MAX_SIZE}
      ALLOW_FORMATS: ${file(./.env.yml):ALLOW_FORMATS}
  show:
    handler: handlers/api.show
    events:
      - http:
          path: thumbs/{id}
          method: get
          cors: true
          request: 
            parameters:
               paths: 
                 id: true
  resize:
    handler: handlers/process.resize
    events:
      - s3:
          bucket: ${file(./.env.yml):BUCKET}
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
          existing: true